const Map<String, String> preAuthDefaultTextContents = {
  // Common
  'common.error_prefix': 'Error',
  'common.open_link_failed': 'Unable to open link',
  'common.open_contact_failed': 'Unable to open contact action',
  'common.phone_call_failed': 'Unable to place the call',
  'common.proceed': 'Proceed',
  'common.submit': 'Submit',
  'common.unknown_error': 'An unknown error occurred.',
  'common.loading': 'Loading...',
  'common.delete': 'Delete',
  'common.save': 'Save',
  'common.create': 'Create',
  'common.edit': 'Edit',
  'common.back': 'Back',
  'common.description': 'Description',
  'common.title': 'Title',
  'common.content': 'Content',
  'common.enabled': 'Enabled',
  'common.active': 'Active',
  'common.close': 'Close',
  'common.download': 'Download',
  'common.send': 'Send',
  'common.search': 'Search',
  'common.step': 'Step',
  'common.of': 'of',
  'common.all': 'All',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.male': 'Male',
  'common.female': 'Female',
  'common.individual': 'Individual',
  'common.married': 'Married',
  'common.approved': 'Approved',
  'common.pending_approval': 'Pending approval',
  'common.not_provided': 'Not provided',
  'common.font_size': 'Font size',
  'common.small': 'Small',
  'common.medium': 'Medium',
  'common.large': 'Large',
  'common.open_location': 'Open location',

  // Auth / entry
  'auth.login': 'Login',
  'auth.register': 'Register',
  'auth.request_access': 'Request Access',
  'auth.forgot_password': 'Forgot Password ?',
  'auth.forgot_password_title': 'Forgot Password',
  'auth.email_label': 'Email',
  'auth.email_invalid': 'Please enter a valid email.',
  'auth.send_reset_email': 'Send Reset Email',
  'auth.reset_email_sent': 'Password reset email sent. Check your inbox.',
  'auth.login_validation': 'Please fill all fields (password min 6 chars)',
  'auth.name_label': 'Your Name',
  'auth.name_helper': 'Name should have only characters, not numbers',
  'auth.name_required': 'Please enter your name',
  'auth.name_min_length': 'Name must be at least 3 characters',
  'auth.email_address_label': 'Email Address',
  'auth.email_required': 'Please enter your email',
  'auth.email_address_invalid': 'Please enter a valid email address',
  'auth.phone_label': 'Phone Number',
  'auth.phone_required': 'Please enter your phone number',
  'auth.phone_invalid': 'Enter a valid 10-digit phone number',
  'auth.location_label': 'Google Maps Location',
  'auth.location_helper': 'Use current location or paste your Google Maps link',
  'auth.location_required': 'Please enter your location',
  'auth.location_use_current': 'Use Current Location',
  'auth.location_permission_denied': 'Location permission denied',
  'auth.location_permission_denied_forever':
      'Location permission denied permanently. Enable it from settings.',
  'auth.location_service_disabled': 'Location services are disabled',
  'auth.location_fetch_failed': 'Unable to fetch current location',
  'auth.address_label': 'Address',
  'auth.address_helper': 'Enter your address manually',
  'auth.address_required': 'Please enter your address',
  'auth.gender_label': 'Gender',
  'auth.gender_required': 'Please select your gender',
  'auth.category_label': 'Category',
  'auth.category_required': 'Please select your category',
  'auth.family_existing_toggle': 'Use existing family ID',
  'auth.family_id_label': 'Family ID',
  'auth.family_id_required': 'Please select or create a family ID',
  'auth.family_name_label': 'Family Name',
  'auth.family_name_helper': 'Used to generate a new family ID',
  'auth.family_name_required': 'Please enter a family name',
  'auth.individual_family_hint': 'Family ID will be generated automatically',
  'auth.dob_label': 'Date of Birth',
  'auth.dob_hint': 'Select your date of birth',
  'auth.dob_select': 'Select date of birth',
  'auth.age_label': 'Age',
  'auth.age_hint': 'Select DOB to calculate age',
  'auth.dob_required': 'Please select your date of birth',
  'auth.birthday_label': 'Birthday',
  'auth.birthday_hint': 'Select your birthday',
  'auth.password_label': 'Password',
  'auth.password_helper': 'Min 8 chars, 1 uppercase, 1 number',
  'auth.password_required': 'Please enter a password',
  'auth.password_min_length': 'Password must be at least 8 characters',
  'auth.password_uppercase_required': 'Include at least one uppercase letter',
  'auth.password_number_required': 'Include at least one number',
  'auth.confirm_password_label': 'Confirm Password',
  'auth.confirm_password_helper': 'Password and Confirm passwords must be same',
  'auth.confirm_password_required': 'Please confirm your password',
  'auth.passwords_mismatch': 'Passwords do not match',
  'auth_entry.welcome': 'Welcome',
  'auth_entry.continue': 'Continue',
  'auth.user_not_found_title': 'User not found',
  'auth.user_not_found_message':
      'No registered user was found for this church. Would you like to register as a new user?',
  'auth.no_account_found_request_access':
      'No account was found for this church. Do you want to request access?',
  'auth.login_screen_email_required': 'Please enter your email address.',
  'auth.login_screen_password_required': 'Please enter your password.',
  'auth.login_fetch_user_failed': 'Unable to fetch logged in user',
  'auth.welcome_back_heading': 'Welcome back',
  'auth.create_account_heading': 'Create your Church Tree account',
  'auth.login_subtitle': 'Sign in with your Church Tree account to continue.',
  'auth.register_subtitle':
      'Create your Church Tree first, then request access to your church.',
  'auth.login_toggle_register': 'Need a new Church Tree account? Register',
  'auth.register_toggle_login': 'Already have a Church Tree account? Login',

  // Onboarding / bootstrap
  'onboarding.get_started': 'Get Started',
  'onboarding.next': 'Next',
  'app.bootstrap_failed': 'Bootstrap Launch failed',
  'notifications.not_now': 'Not now',
  'notifications.enable': 'Enable',

  // Church selection
  'church.select_subtitle': 'Select your church to proceed further',
  'church.select_button': 'Select Church',
  'church.select_action': 'Select Church',
  'church.error_loading': 'Error loading churches',
  'church.none_available': 'No churches available',
  'church.register_your_church': 'Register your church',
  'church.welcome_home': 'Welcome Home',
  'church.select_helper':
      "We'll help you find a local congregation to stay connected with services, events, and news.",
  'church.register_coming_soon': 'Register your church coming soon',
  'church.register_subtitle':
      'Share your church details. It will stay hidden until a super admin approves it.',
  'church.register_loading': 'Registering church...',
  'church.register_duplicate_email': 'A church with this email already exists.',
  'church.register_success_pending':
      'Church registered successfully. It will appear after super admin approval.',
  'church.directory_title': 'Churches',
  'church.directory_load_error': 'We could not load the church list right now.',
  'church.your_churches_title': 'Your Churches',
  'church.your_churches_subtitle': "Churches you follow and you're part of.",
  'church.your_churches_empty_subtitle':
      "Churches you follow and you're part of will show here.",
  'church.your_churches_empty_state':
      'You are not part of any church yet. Use the section below to explore other churches.',
  'church.other_churches_title': 'Other Churches',
  'church.other_churches_subtitle':
      'Explore other churches. Tapping one lets you submit a request form, and once an admin approves it, enrollment will be smoother.',
  'church.other_churches_empty_state':
      'You already belong to every available church in the directory.',
  'church.detail_pastor': 'Pastor',
  'church.detail_email': 'Email',
  'church.detail_contact': 'Contact',
  'church.detail_address': 'Address',

  // Drawer
  'drawer.title': 'Church',
  'drawer.error_loading_user': 'Error loading user',
  'drawer.logout': 'Logout',

  // Super admin
  'super_admin.title': 'Super Admin',
  'super_admin.subtitle':
      'Manage platform-level churches before entering the church app.',
  'super_admin.choose_flow_title': 'Choose your flow',
  'super_admin.choose_flow_subtitle':
      'You have super admin access. Continue with the normal church flow or open the super admin space.',
  'super_admin.normal_flow': 'Normal Flow',
  'super_admin.normal_flow_desc':
      'Go to church selection and continue like a regular signed-in user.',
  'super_admin.super_flow': 'Super Admin Flow',
  'super_admin.super_flow_desc':
      'Open the platform-level church management dashboard.',
  'super_admin.open_church_selection': 'Open Church Selection',
  'super_admin.open_dashboard': 'Open Super Admin',
  'super_admin.back_to_normal_flow': 'Back To Church Selection',
  'super_admin.create_church': 'Create Church',
  'super_admin.create_church_coming_soon': 'Create church flow coming soon',
  'super_admin.create_church_title': 'Create Church',
  'super_admin.create_church_subtitle':
      'Create a new church and bootstrap the essential starter structure.',
  'super_admin.church_name_label': 'Church Name',
  'super_admin.church_id_label': 'Church ID',
  'super_admin.church_id_helper':
      'Lowercase letters, numbers, and underscores only.',
  'super_admin.church_id_auto_hint':
      'Church ID will be generated automatically from the church name.',
  'super_admin.church_id_preview': 'Generated Church ID',
  'super_admin.pastor_name_label': 'Pastor Name',
  'super_admin.admin_name_label': 'Admin Name',
  'super_admin.admin_email_label': 'Admin Email',
  'super_admin.admin_phone_label': 'Admin Phone',
  'super_admin.admin_section_title': 'Initial Admin',
  'super_admin.address_label': 'Address',
  'super_admin.contact_label': 'Contact',
  'super_admin.email_label': 'Email',
  'super_admin.logo_label': 'Church Logo',
  'super_admin.logo_pick': 'Pick Logo',
  'super_admin.logo_replace': 'Replace Logo',
  'super_admin.logo_required': 'Please pick a church logo',
  'super_admin.pastor_photo_label': 'Pastor Photo',
  'super_admin.pastor_photo_pick': 'Pick Pastor Photo',
  'super_admin.pastor_photo_replace': 'Replace Pastor Photo',
  'super_admin.pastor_photo_required': 'Please pick a pastor photo',
  'super_admin.enabled_label': 'Enabled',
  'super_admin.create_action': 'Create Church',
  'super_admin.create_loading': 'Creating church...',
  'super_admin.create_success':
      'Church created successfully. Password setup email sent to the admin.',
  'super_admin.create_success_email_failed':
      'Church created successfully, but the password setup email could not be sent to the admin.',
  'super_admin.name_required': 'Please enter the church name',
  'super_admin.id_required': 'Please enter the church ID',
  'super_admin.id_invalid':
      'Church ID can contain only lowercase letters, numbers, and underscores',
  'super_admin.duplicate_id': 'A church with this ID already exists',
  'super_admin.address_required': 'Please enter the church address',
  'super_admin.contact_required': 'Please enter the church contact',
  'super_admin.email_required': 'Please enter the church email',
  'super_admin.admin_name_required': 'Please enter the admin name',
  'super_admin.admin_email_required': 'Please enter the admin email',
  'super_admin.admin_phone_required': 'Please enter the admin phone',
  'super_admin.directory_title': 'All Churches',
  'super_admin.directory_empty': 'No churches found yet.',
  'super_admin.search_hint': 'Search churches',
  'super_admin.total_count': 'Total',
  'super_admin.enabled_count': 'Enabled',
  'super_admin.disabled_count': 'Disabled',
  'super_admin.disabled_label': 'Disabled',
  'super_admin.status_updated': 'Church status updated',
};

const Map<String, String> defaultChurchTextContents = {
  // Feed screen / modal
  'feed.error_load': 'Unable to load feed',
  'feed.no_church_selected': 'No church selected',
  'feed.retry': 'Retry',
  'feed.no_posts': 'No posts yet',
  'feed.create_title': 'Create Post',
  'feed.edit_title': 'Edit Post',
  'feed.cancel': 'Cancel',
  'feed.add_image_optional': 'Add Image (Optional)',
  'feed.validation_all_fields_required': 'All fields are required',
  'feed.image_required': 'An image is required for this post',
  'feed.title_label': 'Title',
  'feed.description_label': 'Description',
  'feed.global_share_details_title': 'Share personal details',
  'feed.global_share_details_enabled':
      'Name, category, address, DOB, email, and phone will be available from this global post.',
  'feed.global_share_details_disabled':
      'Only name, church, and church pastor will be shown from this global post.',
  'feed.change_image': 'Change Image',
  'feed.post_deleted': 'Post deleted',
  'feed.post_action': 'Post',
  'feed.update_action': 'Update',
  'feed.delete_action': 'Delete Post',
  'feed.edit_post': 'Edit post',
  'feed.delete_post': 'Delete post',
  'feed.delete_confirm_title': 'Delete post?',
  'feed.delete_confirm_message':
      'This will permanently delete the post and its image.',

  // Settings
  'settings.title': 'Settings',
  'settings.dark_mode': 'Dark Mode',
  'settings.prayer_reminders': 'Prayer Reminders',
  'settings.prayer_daily_at_prefix': 'Daily at',
  'settings.prayer_reminders_subtitle_off': 'Enable daily prayer reminder',
  'settings.edit_reminder_time': 'Edit Reminder Time',
  'settings.clear_local_data': 'Clear All Local Data',
  'settings.confirm': 'Confirm',
  'settings.clear_confirm_message':
      'Are you sure you want to clear all local data?',
  'settings.cancel': 'Cancel',
  'settings.clear': 'Clear',
  'settings.local_data_cleared': 'All local data cleared',
  'settings.prayer_schedule_failed': 'Failed to schedule reminder',
  'settings.edit_profile': 'Review Profile',
  'settings.profile_updated': 'Profile updated',
  'settings.delete_account': 'Delete Account',
  'settings.delete_account_subtitle':
      'Remove your profile from the selected church',
  'settings.delete_account_message':
      'This removes your profile from the currently selected church and takes you back to church selection.',
  'settings.delete_account_no_church': 'No church selected.',
  'settings.push_notifications': 'Push Notifications',
  'settings.push_enabled': 'Enabled and synced for church updates',
  'settings.push_provisional': 'Enabled with provisional permission',
  'settings.push_not_determined': 'Not enabled yet',
  'settings.push_blocked': 'Blocked at system level. Open settings to enable.',
  'settings.push_manage': 'Manage',
  'settings.push_enable': 'Enable',
  'settings.push_refresh': 'Refresh',
  'settings.push_not_signed_in': 'Sign in to manage push notifications',
  'settings.push_no_church': 'Select a church before enabling notifications',
  'settings.push_status_unavailable':
      'Unable to check notification status right now',
  'approval.pending_title': 'Approval Pending',
  'approval.waiting_title': 'Your access is waiting for approval',
  'approval.waiting_message':
      'If an admin turned access off for this church, you can refresh your status here or go back and choose another church so you are not blocked.',

  // Section headers
  'for_you.article.section_title': 'Article Notes',
  'for_you.reading_plan.section_title': 'Reading Plans',
  'for_you.featured.plans_section_title': 'Plans for you ✮',
  'for_you.featured.section_title': 'Featured for you ✮',
  'promise.section_title': 'Promise Word 2026',

  // Members
  'members.title': 'All Members ',
  'members.error_loading': 'Error loading members',
  'members.none': 'No members found',
  'members.delete_title': 'Delete member?',
  'members.delete_message': 'This will remove the member from this church.',
  'members.delete_success': 'Member deleted',
  'members.edit_category_title': 'Edit category',
  'members.edit_category_action': 'Edit Category',
  'members.edit_category_success': 'Category updated',
  'members.no_families_available':
      'No families are available for this church yet.',
  'members.create_member_login_title': 'Create Member Login',
  'members.create_member_login_heading': 'Create member login',
  'members.create_member_login_subtitle':
      'Create a Church Tree login for this member.',
  'members.create_member_account_heading': 'Create member account',
  'members.create_member_account_subtitle':
      'Enter the member email. We will create the account and send a password setup email.',
  'members.create_member_email_helper':
      'Church Account will use this email and block duplicate accounts automatically.',
  'members.create_member_login_success': 'Member login created successfully.',
  'members.create_member_password_email_sent':
      ' Password setup email sent to the member.',
  'members.create_member_password_email_failed':
      ' Member login created, but the password setup email could not be sent.',
  'members.create_member_login_action': 'Create member login',
  'members.create_member_account_action': 'Create member account',
  'members.create_member_login_footer':
      'This will create login access and send a password setup email.',
  'members.create_member_account_footer':
      'Member account will be created with this email and Church Account will send a password setup email.',
  'members.search_hint': 'Search members, family ID, email or phone',
  'members.all_tab': 'All',
  'members.families_tab': 'Families',
  'members.individuals_tab': 'Individuals',
  'members.birthdays_tab': 'Birthdays',
  'members.no_birthdays_today': 'No birthdays today',
  'members.no_matching_members': 'No matching members',
  'members.no_family_groups_found': 'No family groups found',
  'members.member_count_suffix': 'member(s)',
  'members.approve_member': 'Approve member',
  'members.basic_details_title': 'Basic Details',
  'members.basic_details_subtitle':
      'Capture the member information in one place.',
  'members.extended_information_title': 'Extended Information',
  'members.extended_information_subtitle':
      'Capture financial, educational and gifting details.',
  'members.church_groups_title': 'Church Groups',

  // For You / Featured
  'for_you.featured.plan_badge': 'Challenge Yourself to do',
  'for_you.featured.plan_title': 'Bible in a year',
  'for_you.featured.plan_description':
      "Reading the Bible in a year won't just change what you know; it will change how you think. You are trading 15 minutes of scrolling for a lifetime of wisdom",
  'for_you.featured.plan_button': 'Explore Now',
  'for_you.featured.youtube_title':
      'Deepen the Word, One Video at a Time. Follow us on YouTube.',
  'for_you.featured.youtube_button': 'Start Watching',
  'for_you.featured.swipe_title':
      'Got 2 minutes? That’s enough to fuel your soul. Swipe some verses.',
  'for_you.featured.swipe_button': 'Let’s Go',
  'members.church_groups_subtitle':
      'Select the ministries and teams this member belongs to.',
  'members.request_basic_details_subtitle':
      'Capture your basic details before submitting your request.',
  'members.review_title': 'Review',
  'members.review_subtitle':
      'Check the details before submitting your request.',
  'members.member_name_required': 'Please enter the member name',
  'members.member_address_required': 'Please enter the member address',
  'members.member_wedding_day_required': 'Please select the wedding day',
  'members.member_gender_required': 'Please select the member gender',
  'members.member_dob_required': 'Please select the member date of birth',
  'members.marital_status_required': 'Please select your marital status',
  'members.wedding_day_required': 'Please select your wedding day',
  'members.account_required_before_request':
      'Create your account first before requesting access.',
  'members.member_updated_success': 'Member updated successfully.',
  'members.member_created_success': 'Member created successfully.',
  'members.marital_status_label': 'Marital Status',
  'members.wedding_day_label': 'Wedding Day',
  'members.wedding_day_hint': 'Select wedding day',
  'members.contact_label': 'Contact',
  'members.name_label': 'Name',
  'members.phone_label': 'Phone',
  'members.email_label': 'Email',
  'members.gender_label': 'Gender',
  'members.category_label': 'Category',
  'members.family_id_label': 'Family ID',
  'members.family_name_label': 'Family Name',
  'members.address_label': 'Address',
  'members.date_of_birth_label': 'Date of Birth',
  'members.financial_stability_label': 'Financial Stability',
  'members.financial_stability_rating':
      'Financial Stability Rating: {rating}/5',
  'members.financial_not_rated': 'Not rated',
  'members.financial_support_required': 'Financial Support Required',
  'members.educational_qualification': 'Educational Qualification',
  'members.talents_and_gifts': 'Talents & Gifts',
  'members.talents_and_gifts_helper': 'Add comma-separated talents or gifts',
  'members.no_church_groups_assigned': 'No church groups assigned',
  'members.create_with_email': 'Create with email',
  'members.create_with_email_subtitle':
      'Create Church Tree account first, then complete member details.',
  'members.create_without_email': 'Create without email',
  'members.create_without_email_subtitle':
      'Add the member directly using church details only.',
  'members.create_church_connect_account': 'Create Church Tree account?',
  'members.create_church_connect_account_message':
      'This member does not have a Church Tree account yet. Do you want to create it first?',
  'members.no_family_id': 'No Family ID',
  'members.unknown_family': 'Unknown family',
  'groups.empty_state': 'No church groups are assigned yet.',
  'groups.add_to_group': 'Add to {group}',
  'groups.all_members_assigned':
      'All members are already assigned to this group.',
  'groups.member_added': '{member} added to {group}',
  'groups.remove_from_group': 'Remove from {group}',
  'groups.remove_from_group_message':
      'This removes the member only from this group.',
  'groups.member_removed': '{member} removed from {group}',
  'groups.group_load_failed': 'Unable to load this group right now.',
  'groups.group_member_count': '{count} members in this group',
  'groups.tab_load_failed': 'Unable to load {group}.',
  'groups.empty_group_members': 'No members are assigned to this group yet.',

  // Settings / profile
  'settings.loading_profile': 'Loading...',
  'settings.error_loading_profile': 'Error: {error}',
  'settings.edit_profile_title': 'Edit Profile',
  'settings.profile_phone_invalid': 'Enter a valid 10-digit phone number',
  'settings.profile_address_location_required':
      'Address and maps location are required',
  'settings.profile_birthday_required': 'Please select your birthday',

  // Birthday posts
  'birthday.title_required': 'Title and description are required',
  'birthday.image_pending': 'Birthday image is still being prepared',
  'birthday.title_label': 'Title',
  'birthday.description_label': 'Description',
  'birthday.date_unavailable': 'Birthday date unavailable',
  'birthday.date_prefix': 'Birthday',
  'birthday.card_no_verse': 'No verse available right now.',
  'birthday.card_title': 'BIRTHDAY WISHES',
  'birthday.save_image': 'Save as Image',

  // Verse share
  'verse_share.footer_date_note':
      'The current date is always shown on the card.',
  'verse_share.footer_color': 'Footer Color',
  'verse_share.bottom_left_text_optional': 'Bottom-left text (optional)',
  'verse_share.story_footer_helper': 'Only shown in story mode',
  'verse_share.story_footer_note':
      'Switch to story mode if you want to add an optional footer note.',

  // Studio
  'studio.chapter_prefix': 'Chapter',
  'studio.verse_prefix': 'Verse',

  // Favorites
  'favorites.title': 'Favorites',
  'favorites.none': 'No Favorites yet',
  'favorites.removed': 'Removed from favorites',
  'favorites.share_english': 'Share in English',
  'favorites.share_tamil': 'Share in Tamil',

  // Prayer requests
  'prayer.my_requests_title': 'My Prayer Requests',
  'prayer.all_requests_title': 'All Prayer Requests',
  'prayer.my_requests_tab': 'My Requests',
  'prayer.all_requests_tab': 'All Requests',
  'prayer.none': 'No prayer requests yet',
  'prayer.by_loading': 'By: Loading...',
  'prayer.by_unknown': 'By: Unknown',
  'prayer.expires_prefix': 'Expires',
  'prayer.modal_title': 'Prayer Request',
  'prayer.title_label': 'Title',
  'prayer.title_required': 'Title required',
  'prayer.description_label': 'Description',
  'prayer.description_required': 'Description required',
  'prayer.submit_anonymous': 'Submit anonymously',
  'prayer.select_expiry_date': 'Select expiry date',
  'prayer.expiry_prefix': 'Expiry',
  'prayer.select_expiry_required': 'Please select expiry date',
  'prayer.saved_success': 'Prayer request saved successfully',

  // About
  'about.our_mission': 'Our Mission',
  'about.our_community': 'Our Community',
  'about.our_values': 'Our Values',

  // Events / announcements / pastors
  'events.title': 'Events',
  'events.section_title': 'Events',
  'events.none': 'No Events',
  'announcements.section_title': 'Announcements',
  'announcements.none': 'No announcements',
  'pastor.section_title': 'Our Pastors',
  'pastor.empty_error': 'Something went wrong',

  // Bible / reading plan
  'bible.title': 'Holy Bible',
  'bible_swipe.title': 'Bible Swipes',
  'reading_plan.title': 'Bible in a year',
  'approval.refresh_status': 'Refresh Status',
  'approval.choose_another_church': 'Choose Another Church',

  // Birthday modal
  'birthday.today_title': "Today's Birthdays",
  'birthday.none_subtitle': 'No members have birthdays today.',
  'birthday.pick_member_subtitle':
      'Choose a member to prepare a birthday post.',
  'birthday.none_today': 'No birthdays today',
  'birthday.post_title': 'Birthday Post',
  'birthday.close': 'Close',
  'birthday.verse_load_error': 'Unable to load birthday verse:',
  'birthday.no_verse_available':
      'No verse available for birthday posts right now.',
  'birthday.image_preview': 'Image preview',
  'birthday.image_preparing': 'Preparing image...',
  'birthday.image_ready': 'Birthday image ready',
  'birthday.post_wish': 'Post Birthday Wish',

  // Verse share
  'verse_share.layout': 'Edit',
  'verse_share.style': 'Style',
  'verse_share.footer': 'Footer',
  'verse_share.format': 'Format',
  'verse_share.square': 'Square',
  'verse_share.story': 'Story',
  'verse_share.background': 'Background',
  'verse_share.color': 'Color',
  'verse_share.image': 'Image',
  'verse_share.choose_image': 'Choose image',
  'verse_share.replace_image': 'Replace image',
  'verse_share.blur': 'Blur',
  'verse_share.font_size': 'Font Size',
  'verse_share.font_style': 'Font Style',
  'verse_share.font_weight': 'Font Weight',
  'verse_share.font_color': 'Font Color',
  'verse_share.default_font': 'Default',
  'verse_share.serif_font': 'Serif',
  'verse_share.sans_font': 'Sans',
  'verse_share.mono_font': 'Mono',
  'verse_share.rounded_font': 'Rounded',
  'verse_share.bold': 'Bold',
  'verse_share.normal': 'Normal',
  'verse_share.italic': 'Italic',

  // Church tab
  'church_tab.app_title': '',
  'church_tab.home': 'Home',
  'church_tab.for_you': 'For You',
  'church_tab.feeds': 'Feeds',

  // Studio
  'studio.title': 'Studio',
  'studio.admin_only': 'Studio is available only for admins.',
  'studio.no_church_selected': 'No church selected.',
  'studio.tab_theme': 'Theme',
  'studio.tab_about': 'About',
  'studio.tab_pastor': 'Pastor',
  'studio.tab_bible_swipe': 'Bible Swipe',
  'studio.tab_footer': 'Footer',
  'studio.tab_events': 'Events',
  'studio.tab_announcements': 'Announcements',
  'studio.tab_daily_verse': 'Daily Verse',
  'studio.tab_articles': 'Articles',
  'studio.tab_promise': 'Promise',
  'studio.tab_notifications': 'Notifications',
  'studio.tab_admins': 'Admins',
  'studio.tab_admin_mode': 'Admin Mode',
  'studio.tab_sections': 'Sections',
  'studio.tab_prompt': 'Important',
  'studio.add_event': 'Add event',
  'studio.add_pastor': 'Add pastor',
  'studio.no_events': 'No events yet.',
  'studio.no_pastors': 'No pastors yet.',
  'studio.add_announcement': 'Add announcement',
  'studio.no_announcements': 'No announcements yet.',
  'studio.add_article': 'Add article',
  'studio.no_articles': 'No articles yet.',
  'studio.theme_hint':
      'Update the church primary and secondary brand colors using hex values like #1E88E5.',
  'studio.theme_palette_hint':
      'Tap a color from the palette or enter a custom hex value.',
  'studio.theme_primary_label': 'Primary Color',
  'studio.theme_secondary_label': 'Secondary Color',
  'studio.theme_invalid_hex': 'Use valid hex colors like #1E88E5.',
  'studio.theme_updated': 'Theme colors updated',
  'studio.about_hint': 'Update the main about section shown for this church.',
  'studio.about_edit': 'Edit About',
  'studio.about_updated': 'About updated',
  'studio.about_church_name': 'Church Name',
  'studio.about_tagline': 'Tagline',
  'studio.about_mission': 'Mission',
  'studio.about_community': 'Community',
  'studio.about_values': 'Values',
  'studio.bible_swipe_hint':
      'Enter one verse reference per line, like John 3:16.',
  'studio.bible_swipe_empty': 'No swipe verses added yet.',
  'studio.bible_swipe_add': 'Add Swipe Verse',
  'studio.bible_swipe_edit': 'Edit Swipe Verses',
  'studio.bible_swipe_edit_single': 'Edit Swipe Verse',
  'studio.bible_swipe_label': 'Swipe verses',
  'studio.bible_swipe_updated': 'Bible swipe verses updated',
  'studio.footer_contacts_title': 'Footer Contacts',
  'studio.footer_contacts_add': 'Add contact item',
  'studio.footer_contacts_empty': 'No footer contact items yet.',
  'studio.footer_social_title': 'Footer Social',
  'studio.footer_social_add': 'Add social item',
  'studio.footer_social_empty': 'No social items yet.',
  'studio.footer_type_prefix': 'Type',
  'studio.footer_action_prefix': 'Action',
  'studio.footer_order_prefix': 'Order',
  'studio.footer_active_prefix': 'Active',
  'studio.footer_platform_prefix': 'Platform',
  'studio.footer_url_prefix': 'URL',
  'studio.footer_contact_create': 'Add Contact Item',
  'studio.footer_contact_edit': 'Edit Contact Item',
  'studio.footer_social_create': 'Add Social Item',
  'studio.footer_social_edit': 'Edit Social Item',
  'studio.footer_type_label': 'Type',
  'studio.footer_label_label': 'Label',
  'studio.footer_action_label': 'Action',
  'studio.footer_order_label': 'Order',
  'studio.footer_icon_label': 'Icon Label',
  'studio.footer_platform_label': 'Platform',
  'studio.footer_url_label': 'URL',
  'studio.section_home': 'Home Sections',
  'studio.section_for_you': 'For You Sections',
  'studio.section_enabled': 'Enabled',
  'studio.section_disabled': 'Disabled',
  'studio.section_order': 'Order',
  'studio.section_updated': 'Section updated',
  'studio.section_announcements': 'Announcements',
  'studio.section_events': 'Events',
  'studio.section_promise': 'Promise',
  'studio.section_footer': 'Footer',
  'studio.section_daily_verse': 'Daily Verse',
  'studio.section_featured': 'Featured',
  'studio.section_article': 'Article',
  'studio.delete_title': 'Delete',
  'studio.delete_confirm_remove_prefix': 'Remove',
  'studio.event_type_prefix': 'Type',
  'studio.event_contact_prefix': 'Contact',
  'studio.event_location_prefix': 'Location',
  'studio.announcement_priority_prefix': 'Priority',
  'studio.edit_item_prefix': 'Edit',
  'studio.notification_title': 'Church Topic Notification',
  'studio.notification_topic_prefix': 'Topic',
  'studio.notification_title_label': 'Notification title',
  'studio.notification_body_label': 'Notification body',
  'studio.notification_queued': 'Notification request queued',
  'studio.notification_send': 'Send Notification',
  'studio.admins_hint': 'Enter one admin email per line.',
  'studio.admins_label': 'Admin emails',
  'studio.admins_updated': 'Admins updated',
  'studio.admins_save': 'Save Admins',
  'studio.admin_mode_description':
      'Temporarily pause the church app for regular users while updates are in progress.',
  'studio.admin_mode_toggle': 'Turn on admin mode',
  'studio.admin_mode_hint':
      'When enabled, regular users will see a temporary update screen. Admins can still access the app.',
  'studio.admin_mode_updated': 'Admin mode updated',
  'studio.admin_mode_save': 'Save Admin Mode',
  'admin_mode.message': "We're updating {churchName}. Please check back soon.",
  'admin_mode.okay': 'Okay',
  'super_admin.disabled_message':
      'Your church is disabled temporarily. Please contact super admin.',
  'studio.prompt_title': 'Important',
  'studio.prompt_description':
      'This controls the important pop-up card shown to members for urgent announcements or special updates.',
  'studio.prompt_updated': 'Important updated',
  'studio.prompt_save': 'Save Important',
  'studio.announcement_create': 'Create announcement',
  'studio.announcement_edit': 'Edit announcement',
  'studio.announcement_body': 'Body',
  'studio.announcement_upload_image': 'Upload image',
  'studio.announcement_replace_image': 'Replace image',
  'studio.announcement_change_image': 'Change image',
  'studio.priority_label': 'Priority',
  'studio.event_create': 'Create event',
  'studio.event_edit': 'Edit event',
  'studio.event_type': 'Type',
  'studio.event_type_family': 'family',
  'studio.event_type_kids': 'kids',
  'studio.event_type_youth': 'youth',
  'studio.event_contact': 'Contact',
  'studio.event_location': 'Location',
  'studio.event_timing': 'Timing',
  'studio.pastor_create': 'Add Pastor',
  'studio.pastor_edit': 'Edit Pastor',
  'studio.article_create': 'Create article',
  'studio.article_edit': 'Edit article',
  'studio.verse_book': 'Book',
  'studio.verse_chapter': 'Chapter',
  'studio.verse_verse': 'Verse',
};
