// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCdWKenqttG6gI4h5pG1FRthWzLbCNBU',
    appId: '1:527118580197:web:813d4a31d13b20f586d70c',
    messagingSenderId: '527118580197',
    projectId: 'flutterlearning-c9f6c',
    authDomain: 'flutterlearning-c9f6c.firebaseapp.com',
    storageBucket: 'flutterlearning-c9f6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofJFCgZXrA7WC1_tHZOEzquNiqAeBNAs',
    appId: '1:527118580197:android:e2a54aa637be8f1f86d70c',
    messagingSenderId: '527118580197',
    projectId: 'flutterlearning-c9f6c',
    storageBucket: 'flutterlearning-c9f6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhxjA1-2o7FVtkwR7t47lFMu2EAcd7u-4',
    appId: '1:527118580197:ios:1e7030eb2c2444a486d70c',
    messagingSenderId: '527118580197',
    projectId: 'flutterlearning-c9f6c',
    storageBucket: 'flutterlearning-c9f6c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhxjA1-2o7FVtkwR7t47lFMu2EAcd7u-4',
    appId: '1:527118580197:ios:1e7030eb2c2444a486d70c',
    messagingSenderId: '527118580197',
    projectId: 'flutterlearning-c9f6c',
    storageBucket: 'flutterlearning-c9f6c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnuXH05iGbeTZm2qmlCVf090hr_-HQ13c',
    appId: '1:527118580197:web:db2b3008c7bc6d3086d70c',
    messagingSenderId: '527118580197',
    projectId: 'flutterlearning-c9f6c',
    authDomain: 'flutterlearning-c9f6c.firebaseapp.com',
    storageBucket: 'flutterlearning-c9f6c.firebasestorage.app',
  );
}
